import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Menu, X, FileText, IdCard, ArrowLeftRight, FileCheck, RefreshCw, FileSignature } from 'lucide-react'
import SarthiDashboard from './Sarthi/components/SarthiDashboard'

const buttonIcons = {
  'DL List': IdCard,
  'Transfer List': ArrowLeftRight,
  'NOC List': FileCheck,
  'Renewal List': RefreshCw,
  'HPA+HPT List': FileSignature,
}

const quickButtons = [
  { title: 'DL List', shortLabel: 'DL', path: '/driving', tone: 'border-indigo-200 bg-indigo-50 text-indigo-700 hover:bg-indigo-100' },
  { title: 'Transfer List', shortLabel: 'Transfer', path: '/vehicle-transfer', tone: 'border-orange-200 bg-orange-50 text-orange-700 hover:bg-orange-100' },
  { title: 'NOC List', shortLabel: 'NOC', path: '/noc', tone: 'border-emerald-200 bg-emerald-50 text-emerald-700 hover:bg-emerald-100' },
  { title: 'Renewal List', shortLabel: 'Renewal', path: '/registration-renewal', tone: 'border-violet-200 bg-violet-50 text-violet-700 hover:bg-violet-100' },
  { title: 'HPA+HPT List', shortLabel: 'HPA+HPT', path: '/hpa-hpt', tone: 'border-rose-200 bg-rose-50 text-rose-700 hover:bg-rose-100' },
]

const Sarthi = () => {
  const navigate = useNavigate()
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  const [isReportModalOpen, setIsReportModalOpen] = useState(false)
  const [dashboardRefreshKey, setDashboardRefreshKey] = useState(0)

  return (
    <>
      {/* Mobile Reports button - only visible on mobile */}
      <div className='lg:hidden fixed top-4 right-4 z-[55]'>
        <button
          onClick={() => setIsReportModalOpen(true)}
          className='flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 text-white rounded-lg shadow-sm hover:bg-blue-700 transition-colors font-bold text-xs'
        >
          <FileText size={16} />
          Reports
        </button>
      </div>

      {/* Mobile Menu button - only visible on mobile */}
      <div className='lg:hidden fixed top-4 left-4 z-[55]'>
        <button
          onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
          className='p-2 rounded-lg bg-white shadow-md hover:bg-slate-100 transition-colors text-slate-600'
          aria-label="Menu"
        >
          {isMobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
        </button>
      </div>

      {/* Report Modal */}
      {isReportModalOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-fadeIn">
           <div className="w-full max-w-lg bg-white rounded-[2rem] shadow-2xl overflow-hidden relative transform transition-all animate-scaleIn">
              <div className="bg-slate-50 px-6 py-5 border-b border-slate-100 flex justify-between items-center">
                 <div className="flex items-center gap-3">
                    <div className="p-2 bg-blue-600 rounded-xl shadow-lg shadow-blue-600/20">
                       <FileText className="text-white" size={20} />
                    </div>
                    <h3 className="text-xl font-black text-slate-800 tracking-tight">System Reports</h3>
                 </div>
                 <button onClick={() => setIsReportModalOpen(false)} className="text-slate-400 hover:text-slate-600 p-2 hover:bg-slate-200 rounded-full transition-all">
                    <X size={20} />
                 </button>
              </div>
              <div className="p-4 grid grid-cols-2 sm:grid-cols-3 gap-3 max-h-[70vh] overflow-y-auto">
                 {quickButtons.map((button) => (
                    <Link
                       key={button.title}
                       to={button.path}
                       onClick={() => setIsReportModalOpen(false)}
                       className={`flex flex-col items-center justify-center p-4 rounded-2xl border transition-all active:scale-95 group ${button.tone}`}
                    >
                       <div className="w-10 h-10 rounded-full bg-white/50 flex items-center justify-center mb-2 shadow-sm group-hover:scale-110 transition-transform">
                          <FileText size={18} />
                       </div>
                       <span className="text-[10px] font-bold uppercase tracking-wider text-center">{button.shortLabel}</span>
                    </Link>
                 ))}
              </div>
              <div className="px-6 py-4 bg-slate-50 border-t border-slate-100 text-center">
                 <p className="text-[10px] text-slate-400 font-bold uppercase tracking-[0.2em]">Generated by RTO Sarthi</p>
              </div>
           </div>
        </div>
      )}

      {/* Mobile Drawer Overlay */}
      {isMobileMenuOpen && (
        <div 
          className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-[55] lg:hidden"
          onClick={() => setIsMobileMenuOpen(false)}
        />
      )}

      {/* Mobile Drawer Content */}
      <aside className={`fixed top-0 left-0 h-full w-72 bg-slate-900 text-white z-[56] transition-transform duration-300 ease-in-out lg:hidden ${isMobileMenuOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="flex flex-col h-full">
          <div className="p-6 border-b border-white/10 flex justify-between items-center">
            <h2 className="font-bold text-lg">Sarthi Options</h2>
            <button onClick={() => setIsMobileMenuOpen(false)} className="p-1 hover:bg-white/10 rounded-lg">
              <X size={20} />
            </button>
          </div>
          <div className="flex-1 overflow-y-auto p-3">
            <div className="grid grid-cols-1 gap-2">
              {quickButtons.map((button) => {
                const Icon = buttonIcons[button.title]
                const btnClass = 'flex flex-col items-center justify-center h-24 border border-white/10 bg-white/5 hover:bg-white/10 hover:scale-[1.04] transition-all duration-200 text-white rounded-lg'
                return (
                  <div key={button.title} className='relative group'>
                    <Link
                      to={button.path}
                      onClick={() => setIsMobileMenuOpen(false)}
                      className={btnClass}
                    >
                      {Icon && (
                        <div className='w-8 h-8 rounded-lg flex items-center justify-center bg-white/10 mb-0.5'>
                          <Icon size={18} className='text-white/80' />
                        </div>
                      )}
                      <span className='text-[10px] font-bold text-center leading-tight'>{button.shortLabel}</span>
                    </Link>
                    <button
                      onClick={(e) => { e.preventDefault(); navigate(button.path); setIsMobileMenuOpen(false); }}
                      className='absolute -top-2 -right-2 w-7 h-7 bg-gray-800 text-white rounded-full shadow-md hover:bg-gray-900 hover:scale-110 transition-all flex items-center justify-center z-10 opacity-0 group-hover:opacity-100'
                      title={`Add ${button.shortLabel}`}
                    >
                      <svg className='w-4 h-4' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                        <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2.5} d='M12 4v16m8-8H4' />
                      </svg>
                    </button>
                  </div>
                )
              })}
            </div>
          </div>
          <div className="p-6 border-t border-white/10 bg-slate-950/50">
             <p className="text-[10px] text-slate-500 uppercase tracking-widest text-center">RTO Sarthi Management</p>
          </div>
        </div>
      </aside>

      <div className='min-h-screen bg-slate-100 px-0.5 pb-8 pt-4 sm:px-4 lg:px-6 lg:pt-5'>
        <div className='flex w-full flex-col gap-6 lg:flex-row lg:max-h-[calc(100vh-5rem)]'>
          <aside className='hidden lg:block lg:w-96 lg:shrink-0 lg:self-start lg:sticky lg:top-4'>
            <div className='bg-white rounded-xl shadow-lg border border-gray-200 p-4'>
              <div className='grid grid-cols-1 gap-3'>
              {quickButtons.map((button) => {
                const Icon = buttonIcons[button.title]
                const btnClass = `flex flex-col items-center justify-center h-24 border transition-all duration-200 hover:scale-[1.04] hover:shadow-md ${button.tone}`
                const inner = (
                  <>
                    {Icon && (
                      <div className='w-10 h-10 rounded-xl flex items-center justify-center bg-white/70 shadow-sm mb-1'>
                        <Icon size={22} className='text-current' />
                      </div>
                    )}
                    <span className='text-xs font-bold text-center leading-tight'>{button.shortLabel}</span>
                  </>
                )
                return (
                  <div key={button.title} className='relative group'>
                    <Link to={button.path} className={btnClass}>{inner}</Link>
                    <button
                      onClick={(e) => { e.preventDefault(); navigate(button.path); }}
                      className='absolute -top-2 -right-2 w-7 h-7 bg-gray-800 text-white rounded-full shadow-md hover:bg-gray-900 hover:scale-110 transition-all flex items-center justify-center z-10 opacity-0 group-hover:opacity-100'
                      title={`Add ${button.shortLabel}`}
                    >
                      <svg className='w-4 h-4' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                        <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2.5} d='M12 4v16m8-8H4' />
                      </svg>
                    </button>
                  </div>
                )
              })}
            </div>
            </div>
          </aside>

          <main id='sarthi-dashboard' className='flex-1 min-w-0 lg:overflow-y-auto'>
            <div className='bg-white rounded-xl sm:rounded-2xl shadow-lg border border-gray-200 flex flex-col h-full'>
              <div className="flex items-center px-4 py-2.5 sm:px-5 sm:py-3 border-b border-gray-100">
                <button
                  onClick={() => navigate('/')}
                  className='flex items-center justify-center w-10 h-10 rounded-xl bg-white border border-gray-200 shadow-sm hover:shadow-md hover:border-indigo-300 transition-all cursor-pointer flex-shrink-0'
                  title='Back to Home'
                >
                  <svg className='w-5 h-5 text-gray-600' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                    <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M10 19l-7-7m0 0l7-7m-7 7h18' />
                  </svg>
                </button>
                <span className="ml-3 text-sm font-semibold text-gray-500">Dashboard</span>
              </div>
              <SarthiDashboard refreshKey={dashboardRefreshKey} />
            </div>
          </main>
        </div>
      </div>
    </>
  )
}

export default Sarthi

